from ultralytics.nn.modules.AddModules.ChannelAwareEdgeEnhance import ChannelAwareEdgeEnhance
from ultralytics.nn.modules.AddModules.SoftFillEdgeEnhance import SoftFillEdgeEnhance
from ultralytics.nn.modules.AddModules.LogWaveletDenoise import LogWaveletDenoise
from ultralytics.nn.modules.AddModules.EFC_FPN import EFC_FPN
from ultralytics.nn.modules.AddModules.PRN_ import PRN
from ultralytics.nn.modules.AddModules.GoldNeck_P234 import GoldNeck_P234
from ultralytics.nn.modules.AddModules.EFCFusion import EFCFusion
from ultralytics.nn.modules.AddModules.C3k2_Sparse import C3k2_Sparse
from ultralytics.nn.modules.AddModules.StarC3k2 import StarC3k2
from ultralytics.nn.modules.AddModules.ASFF import ASFF
from ultralytics.nn.modules.AddModules.SPDWTConv import SPDWTConv
from ultralytics.nn.modules.AddModules.C3k2WT import C3k2WT